"""reconcile schema drift

Revision ID: 0cb53a43798b
Revises: c5d6e7f8a9b0
Create Date: 2026-04-09 07:28:41.657514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cb53a43798b'  # pragma: allowlist secret
down_revision = 'c5d6e7f8a9b0'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def _table_exists(name: str) -> bool:
        return name in inspector.get_table_names()

    def _column_exists(table: str, column: str) -> bool:
        if not _table_exists(table):
            return False
        return column in [col["name"] for col in inspector.get_columns(table)]

    def _fk_exists(table: str, fk_name: str) -> bool:
        if not _table_exists(table):
            return False
        return fk_name in [fk["name"] for fk in inspector.get_foreign_keys(table)]

    tables_to_drop = [
        'search_query_logs',
        'booking_change_policies',
        'provider_availability_rules',
        'booking_timeline_events',
        'provider_blackouts',
        'user_subscriptions',
        'booking_change_requests',
        'reviews',
        'subscription_plans',
        'provider_quotes',
        'fraud_flags',
        'promo_redemptions',
        'provider_instant_book_settings',
        'notification_preferences',
        'quote_messages',
        'chat_insights',
        'favorite_providers',
        'ai_job_intake_logs',
        'quote_request_provider_targets',
        'promo_codes',
        'notifications',
        'booking_disputes',
        'referral_rewards',
        'quote_requests',
        'notification_deliveries',
    ]
    for table in tables_to_drop:
        op.execute(sa.text(f'DROP TABLE IF EXISTS "{table}" CASCADE'))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        if _fk_exists('bookings', batch_op.f('fk_bookings_cancelled_by_user_id')):
            batch_op.drop_constraint(batch_op.f('fk_bookings_cancelled_by_user_id'), type_='foreignkey')
        if _fk_exists('bookings', batch_op.f('fk_bookings_quote_request_id')):
            batch_op.drop_constraint(batch_op.f('fk_bookings_quote_request_id'), type_='foreignkey')
        if _column_exists('bookings', 'original_scheduled_at'):
            batch_op.drop_column('original_scheduled_at')
        if _column_exists('bookings', 'refund_status'):
            batch_op.drop_column('refund_status')
        if _column_exists('bookings', 'cancellation_fee_amount'):
            batch_op.drop_column('cancellation_fee_amount')
        if _column_exists('bookings', 'started_at'):
            batch_op.drop_column('started_at')
        if _column_exists('bookings', 'cancelled_at'):
            batch_op.drop_column('cancelled_at')
        if _column_exists('bookings', 'quote_request_id'):
            batch_op.drop_column('quote_request_id')
        if _column_exists('bookings', 'reschedule_count'):
            batch_op.drop_column('reschedule_count')
        if _column_exists('bookings', 'eta_minutes'):
            batch_op.drop_column('eta_minutes')
        if _column_exists('bookings', 'cancelled_by_user_id'):
            batch_op.drop_column('cancelled_by_user_id')
        if _column_exists('bookings', 'completed_at'):
            batch_op.drop_column('completed_at')
        if _column_exists('bookings', 'arrived_at'):
            batch_op.drop_column('arrived_at')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        if _column_exists('messages', 'summary_tag'):
            batch_op.drop_column('summary_tag')
        if _column_exists('messages', 'attachment_url'):
            batch_op.drop_column('attachment_url')
        if _column_exists('messages', 'read_by'):
            batch_op.drop_column('read_by')

    with op.batch_alter_table('users', schema=None) as batch_op:
        if _column_exists('users', 'is_admin'):
            batch_op.drop_column('is_admin')
        if _column_exists('users', 'service_areas'):
            batch_op.drop_column('service_areas')
        if _column_exists('users', 'portfolio_images'):
            batch_op.drop_column('portfolio_images')
        if _column_exists('users', 'certifications'):
            batch_op.drop_column('certifications')
        if _column_exists('users', 'timezone'):
            batch_op.drop_column('timezone')
        if _column_exists('users', 'specialties'):
            batch_op.drop_column('specialties')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialties', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('certifications', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('portfolio_images', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('service_areas', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_by', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('attachment_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('summary_tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('eta_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reschedule_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quote_request_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cancellation_fee_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('refund_status', postgresql.ENUM('NONE', 'PENDING', 'PROCESSED', 'FAILED', name='refundstatus'), server_default=sa.text("'NONE'::refundstatus"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bookings_quote_request_id'), 'quote_requests', ['quote_request_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_bookings_cancelled_by_user_id'), 'users', ['cancelled_by_user_id'], ['id'])

    op.create_table('notification_deliveries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', postgresql.ENUM('PUSH', 'EMAIL', 'WHATSAPP', 'IN_APP', name='notificationchannel'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'SKIPPED', name='notificationdeliverystatus'), autoincrement=False, nullable=False),
    sa.Column('template_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('template_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_message_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('notification_deliveries_notification_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_deliveries_pkey'))
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_notification_id'), ['notification_id'], unique=False)

    op.create_table('quote_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seeker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('preferred_window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('preferred_window_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('budget_min', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('budget_max', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'WAITING_FOR_PROVIDER', 'WAITING_FOR_SEEKER', 'BOOKED', 'CANCELLED', 'EXPIRED', 'CLOSED', name='quoterequeststatus'), autoincrement=False, nullable=False),
    sa.Column('accepted_provider_quote_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], name=op.f('quote_requests_seeker_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('quote_requests_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quote_requests_pkey'))
    )
    op.create_table('referral_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referred_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'EARNED', 'PAID', name='referralrewardstatus'), autoincrement=False, nullable=False),
    sa.Column('reward_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('referral_rewards_booking_id_fkey')),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name=op.f('referral_rewards_referred_user_id_fkey')),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name=op.f('referral_rewards_referrer_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_rewards_pkey'))
    )
    with op.batch_alter_table('referral_rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_rewards_referrer_user_id'), ['referrer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_rewards_referred_user_id'), ['referred_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_rewards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_rewards_booking_id'), ['booking_id'], unique=False)

    op.create_table('booking_disputes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opened_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='disputestatus'), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refund_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], name=op.f('booking_disputes_assigned_admin_id_fkey')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('booking_disputes_booking_id_fkey')),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], name=op.f('booking_disputes_opened_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_disputes_pkey'))
    )
    with op.batch_alter_table('booking_disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_disputes_opened_by_user_id'), ['opened_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_disputes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_disputes_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_disputes_assigned_admin_id'), ['assigned_admin_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('BOOKING_UPDATE', 'QUOTE_UPDATE', 'PAYMENT_UPDATE', 'CHAT_MENTION', 'PROMOTION', name='notificationcategory'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('deep_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('notifications_recipient_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('promo_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_type', postgresql.ENUM('PERCENT', 'FIXED', name='promodiscounttype'), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('first_booking_only', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('promo_codes_pkey'))
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=True)

    op.create_table('quote_request_provider_targets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_status', postgresql.ENUM('PENDING_RESPONSE', 'QUOTE_SENT', 'NEEDS_INFO', 'DECLINED', 'CLOSED_OTHER_ACCEPTED', 'EXPIRED', name='quotetargetstatus'), autoincrement=False, nullable=False),
    sa.Column('first_notified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('quote_request_provider_targets_provider_id_fkey')),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], name=op.f('quote_request_provider_targets_quote_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quote_request_provider_targets_pkey')),
    sa.UniqueConstraint('quote_request_id', 'provider_id', name=op.f('uq_quote_target'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('quote_request_provider_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_request_provider_targets_response_due_at'), ['response_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_request_provider_targets_quote_request_id'), ['quote_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_request_provider_targets_provider_id'), ['provider_id'], unique=False)

    op.create_table('ai_job_intake_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parsed_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_job_intake_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_job_intake_logs_pkey'))
    )
    with op.batch_alter_table('ai_job_intake_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_job_intake_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_job_intake_logs_created_at'), ['created_at'], unique=False)

    op.create_table('favorite_providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seeker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('favorite_providers_provider_id_fkey')),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], name=op.f('favorite_providers_seeker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_providers_pkey')),
    sa.UniqueConstraint('seeker_id', 'provider_id', name=op.f('uq_favorite_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('favorite_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_providers_seeker_id'), ['seeker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_providers_provider_id'), ['provider_id'], unique=False)

    op.create_table('chat_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extracted_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('quick_replies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('pinned_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_insights_pkey'))
    )
    with op.batch_alter_table('chat_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_insights_room'), ['room'], unique=False)

    op.create_table('quote_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_type', postgresql.ENUM('SEEKER_REPLY', 'PROVIDER_REPLY', 'SYSTEM', name='quotemessagetype'), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], name=op.f('quote_messages_quote_request_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('quote_messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quote_messages_pkey'))
    )
    with op.batch_alter_table('quote_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_messages_quote_request_id'), ['quote_request_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('push_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('whatsapp_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('category_channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quiet_start_local', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('quiet_end_local', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey'))
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('provider_instant_book_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instant_book_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('slot_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot_hold_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled_skill_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('provider_instant_book_settings_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_instant_book_settings_pkey'))
    )
    with op.batch_alter_table('provider_instant_book_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_instant_book_settings_provider_id'), ['provider_id'], unique=True)

    op.create_table('promo_redemptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('promo_redemptions_booking_id_fkey')),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], name=op.f('promo_redemptions_promo_code_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('promo_redemptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('promo_redemptions_pkey'))
    )
    with op.batch_alter_table('promo_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_redemptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_redemptions_promo_code_id'), ['promo_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_redemptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_redemptions_booking_id'), ['booking_id'], unique=False)

    op.create_table('fraud_flags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fraud_flags_booking_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fraud_flags_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fraud_flags_pkey'))
    )
    with op.batch_alter_table('fraud_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_flags_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_flags_booking_id'), ['booking_id'], unique=False)

    op.create_table('provider_quotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('line_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('earliest_available_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'ACCEPTED', 'SUPERSEDED', 'EXPIRED', 'DECLINED', name='providerquotestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('provider_quotes_provider_id_fkey')),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], name=op.f('provider_quotes_quote_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_quotes_pkey')),
    sa.UniqueConstraint('quote_request_id', 'provider_id', 'revision_number', name=op.f('uq_provider_quote_revision'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('provider_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_quotes_quote_request_id'), ['quote_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_quotes_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_quotes_expires_at'), ['expires_at'], unique=False)

    op.create_table('subscription_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('audience', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('billing_period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('priority_support', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reduced_fee_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('loyalty_credit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_plans_pkey'))
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_slug'), ['slug'], unique=True)

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seeker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('punctuality_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('communication_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('reviews_booking_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('reviews_provider_id_fkey')),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], name=op.f('reviews_seeker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_seeker_id'), ['seeker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_booking_id'), ['booking_id'], unique=True)

    op.create_table('booking_change_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_type', postgresql.ENUM('RESCHEDULE', 'CANCEL', name='changerequesttype'), autoincrement=False, nullable=False),
    sa.Column('initiated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'PROCESSING', 'CANCELLED', 'FAILED', name='changerequeststatus'), autoincrement=False, nullable=False),
    sa.Column('reason_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fee_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('refund_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('goodwill_credit_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('booking_change_requests_booking_id_fkey')),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], name=op.f('booking_change_requests_initiated_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('booking_change_requests_resolved_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_change_requests_pkey'))
    )
    with op.batch_alter_table('booking_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_change_requests_resolved_by_user_id'), ['resolved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_change_requests_initiated_by_user_id'), ['initiated_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_change_requests_booking_id'), ['booking_id'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CANCELLED', 'EXPIRED', name='membershipstatus'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('user_subscriptions_plan_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_subscriptions_pkey'))
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_plan_id'), ['plan_id'], unique=False)

    op.create_table('provider_blackouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('provider_blackouts_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_blackouts_pkey'))
    )
    with op.batch_alter_table('provider_blackouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_blackouts_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_blackouts_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_blackouts_end_at'), ['end_at'], unique=False)

    op.create_table('booking_timeline_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('booking_timeline_events_actor_user_id_fkey')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('booking_timeline_events_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_timeline_events_pkey'))
    )
    with op.batch_alter_table('booking_timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_timeline_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_timeline_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_timeline_events_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_timeline_events_actor_user_id'), ['actor_user_id'], unique=False)

    op.create_table('provider_availability_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weekday', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_minute_local', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_minute_local', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buffer_before_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buffer_after_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_notice_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_advance_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('provider_availability_rules_provider_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('provider_availability_rules_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_availability_rules_pkey'))
    )
    with op.batch_alter_table('provider_availability_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_availability_rules_weekday'), ['weekday'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_availability_rules_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_availability_rules_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_availability_rules_enabled'), ['enabled'], unique=False)

    op.create_table('booking_change_policies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('free_cancel_until_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partial_fee_until_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partial_fee_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('partial_fee_min_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('late_fee_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('late_fee_min_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_reschedules', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('booking_change_policies_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_change_policies_pkey'))
    )
    with op.batch_alter_table('booking_change_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_change_policies_provider_id'), ['provider_id'], unique=True)

    op.create_table('search_query_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('result_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clicked_provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booked_provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booked_provider_id'], ['users.id'], name=op.f('search_query_logs_booked_provider_id_fkey')),
    sa.ForeignKeyConstraint(['clicked_provider_id'], ['users.id'], name=op.f('search_query_logs_clicked_provider_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('search_query_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('search_query_logs_pkey'))
    )
    with op.batch_alter_table('search_query_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_query_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_query_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_query_logs_query_text'), ['query_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_query_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_query_logs_clicked_provider_id'), ['clicked_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_query_logs_booked_provider_id'), ['booked_provider_id'], unique=False)

    # ### end Alembic commands ###
