"""add payment intent fields

Revision ID: 0eee5862b4ab
Revises: e8b82813e525
Create Date: 2025-12-07 16:30:34.839826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eee5862b4ab'
down_revision = 'e8b82813e525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('payment_ref')
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
