"""sync models

Revision ID: 1dc791508924
Revises: f803db532601
Create Date: 2026-01-18 06:39:48.035397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc791508924'
down_revision = 'f803db532601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('completed_jobs',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('completed_jobs',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
