"""add selfie filename

Revision ID: 2770b0e5f934
Revises: 1dc791508924
Create Date: 2026-01-18 15:52:19.852454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2770b0e5f934'
down_revision = '1dc791508924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfie_filename', sa.String(length=512), nullable=True))
        batch_op.drop_column('verification_video_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_video_status', postgresql.ENUM('pending', 'verified', 'rejected', 'document_verified', 'face_verified', 'completed', name='verificationstatus'), autoincrement=False, nullable=False))
        batch_op.drop_column('selfie_filename')

    # ### end Alembic commands ###
