"""add kyc workflow

Revision ID: 2a6b96ea439c
Revises: cf9f3f01712b
Create Date: 2026-04-09 09:01:55.197625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '2a6b96ea439c'  # pragma: allowlist secret
down_revision = 'cf9f3f01712b'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    kyc_status_enum = postgresql.ENUM(
        'pending',
        'documents_submitted',
        'under_review',
        'approved',
        'rejected',
        'suspended',
        name='kycstatus',
    )
    kyc_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_documents_provider_id'), ['provider_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_status', sa.Enum('pending', 'documents_submitted', 'under_review', 'approved', 'rejected', 'suspended', name='kycstatus', create_type=False), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('kyc_submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kyc_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kyc_rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kyc_rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kyc_approved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['kyc_approved_by'], ['id'])
        batch_op.alter_column('kyc_status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kyc_approved_by')
        batch_op.drop_column('kyc_rejection_reason')
        batch_op.drop_column('kyc_rejected_at')
        batch_op.drop_column('kyc_approved_at')
        batch_op.drop_column('kyc_submitted_at')
        batch_op.drop_column('kyc_status')

    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_documents_provider_id'))

    op.drop_table('kyc_documents')
    postgresql.ENUM(name='kycstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
