"""Final schema updates

Revision ID: 564cc8a05f3e
Revises: f2a1b3c4d5e6
Create Date: 2026-04-30 14:14:03.663579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564cc8a05f3e'
down_revision = 'f2a1b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quote_requests', ['quote_request_id'], ['id'])

    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_job_posts_status'))

    with op.batch_alter_table('job_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_proposals_status'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_user_read_created', ['recipient_user_id', 'read_at', 'deleted_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_user_read_created')

    with op.batch_alter_table('job_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_proposals_status'), ['status'], unique=False)

    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_posts_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
