"""add consent records and legal account hooks

Revision ID: 7112d2f636fc
Revises: 2a6b96ea439c
Create Date: 2026-04-09 09:45:42.191527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7112d2f636fc'  # pragma: allowlist secret
down_revision = '2a6b96ea439c'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_user_id'))

    op.drop_table('consent_records')
    # ### end Alembic commands ###
