"""Restore missing marketplace schema components

Revision ID: b0cdf505e447
Revises: add_stripe_to_users
Create Date: 2026-04-25 14:01:32.422279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0cdf505e447'
down_revision = 'add_stripe_to_users'
branch_labels = None
depends_on = None


ENUM_DEFINITIONS = {
    "promodiscounttype": ("PERCENT", "FIXED"),
    "notificationcategory": ("BOOKING_UPDATE", "QUOTE_UPDATE", "PAYMENT_UPDATE", "CHAT_MENTION", "PROMOTION"),
    "notificationpriority": ("LOW", "NORMAL", "HIGH", "CRITICAL"),
    "membershipstatus": ("ACTIVE", "CANCELLED", "EXPIRED"),
    "notificationchannel": ("PUSH", "EMAIL", "WHATSAPP", "IN_APP"),
    "notificationdeliverystatus": ("QUEUED", "SENT", "DELIVERED", "FAILED", "SKIPPED"),
    "quoterequeststatus": ("OPEN", "WAITING_FOR_PROVIDER", "WAITING_FOR_SEEKER", "BOOKED", "CANCELLED", "EXPIRED", "CLOSED"),
    "providerquotestatus": ("ACTIVE", "ACCEPTED", "SUPERSEDED", "EXPIRED", "DECLINED"),
    "quotemessagetype": ("SEEKER_REPLY", "PROVIDER_REPLY", "SYSTEM"),
    "quotetargetstatus": ("PENDING_RESPONSE", "QUOTE_SENT", "NEEDS_INFO", "DECLINED", "CLOSED_OTHER_ACCEPTED", "EXPIRED"),
    "disputestatus": ("OPEN", "UNDER_REVIEW", "RESOLVED", "REJECTED"),
    "referralrewardstatus": ("PENDING", "EARNED", "PAID"),
}


def _create_enum_if_missing(bind, name, values):
    if bind.dialect.name != "postgresql":
        return
    values_sql = ", ".join(f"'{value}'" for value in values)
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = '{name}'
            ) THEN
                CREATE TYPE {name} AS ENUM ({values_sql});
            END IF;
        END
        $$;
        """
    )


def _named_enum(bind, name):
    if bind.dialect.name == "postgresql":
        # Do NOT pass values here to avoid SQLAlchemy's DDL generator trying to emit CREATE TYPE
        return postgresql.ENUM(name=name, create_type=False)
    values = ENUM_DEFINITIONS[name]
    return sa.Enum(*values, name=name)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    def _table_exists(name):
        return name in tables

    def _column_exists(table, column):
        if not _table_exists(table):
            return False
        return column in [col["name"] for col in inspector.get_columns(table)]

    for enum_name, enum_values in ENUM_DEFINITIONS.items():
        _create_enum_if_missing(bind, enum_name, enum_values)

    if not _table_exists('chat_insights'):
        op.create_table('chat_insights',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room', sa.String(length=255), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('extracted_address', sa.String(length=255), nullable=True),
        sa.Column('extracted_time', sa.String(length=120), nullable=True),
        sa.Column('quick_replies', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('pinned_summary', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('chat_insights', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_chat_insights_room'), ['room'], unique=True)

    if not _table_exists('promo_codes'):
        op.create_table('promo_codes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=40), nullable=False),
        sa.Column('title', sa.String(length=140), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('discount_type', _named_enum(bind, 'promodiscounttype'), nullable=False),
        sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('usage_limit', sa.Integer(), nullable=True),
        sa.Column('used_count', sa.Integer(), nullable=False),
        sa.Column('city', sa.String(length=120), nullable=True),
        sa.Column('first_booking_only', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('promo_codes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=True)

    if not _table_exists('subscription_plans'):
        op.create_table('subscription_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(length=40), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('audience', sa.String(length=20), nullable=False),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('billing_period', sa.String(length=20), nullable=False),
        sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('priority_support', sa.Boolean(), nullable=False),
        sa.Column('reduced_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('loyalty_credit', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
        )

    if not _table_exists('token_blocklist'):
        op.create_table('token_blocklist',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jti', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    if not _table_exists('ai_job_intake_logs'):
        op.create_table('ai_job_intake_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('raw_text', sa.Text(), nullable=False),
        sa.Column('parsed_payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('ai_job_intake_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_ai_job_intake_logs_user_id'), ['user_id'], unique=False)

    if not _table_exists('booking_change_policies'):
        op.create_table('booking_change_policies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=True),
        sa.Column('free_cancel_until_hours', sa.Integer(), nullable=False),
        sa.Column('partial_fee_until_hours', sa.Integer(), nullable=False),
        sa.Column('partial_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('partial_fee_min_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('late_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('late_fee_min_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('max_reschedules', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('booking_change_policies', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_booking_change_policies_provider_id'), ['provider_id'], unique=True)

    if not _table_exists('notification_preferences'):
        op.create_table('notification_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('push_enabled', sa.Boolean(), nullable=False),
        sa.Column('email_enabled', sa.Boolean(), nullable=False),
        sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
        sa.Column('category_channels', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
        sa.Column('quiet_start_local', sa.String(length=5), nullable=True),
        sa.Column('quiet_end_local', sa.String(length=5), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    if not _table_exists('notifications'):
        op.create_table('notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recipient_user_id', sa.Integer(), nullable=False),
        sa.Column('category', _named_enum(bind, 'notificationcategory'), nullable=False),
        sa.Column('priority', _named_enum(bind, 'notificationpriority'), nullable=False),
        sa.Column('title', sa.String(length=140), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('deep_link', sa.String(length=255), nullable=True),
        sa.Column('entity_type', sa.String(length=64), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('notifications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)

    if not _table_exists('provider_blackouts'):
        op.create_table('provider_blackouts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('start_at', sa.DateTime(), nullable=False),
        sa.Column('end_at', sa.DateTime(), nullable=False),
        sa.Column('reason_code', sa.String(length=32), nullable=False),
        sa.Column('note', sa.String(length=255), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('provider_blackouts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_provider_blackouts_end_at'), ['end_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_provider_blackouts_provider_id'), ['provider_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_provider_blackouts_start_at'), ['start_at'], unique=False)

    if not _table_exists('provider_instant_book_settings'):
        op.create_table('provider_instant_book_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('instant_book_enabled', sa.Boolean(), nullable=False),
        sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
        sa.Column('slot_hold_minutes', sa.Integer(), nullable=False),
        sa.Column('enabled_skill_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('provider_instant_book_settings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_provider_instant_book_settings_provider_id'), ['provider_id'], unique=True)

    if not _column_exists('users', 'profile_photo_url'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=512), nullable=True))

    if not _table_exists('search_query_logs'):
        op.create_table('search_query_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('query_text', sa.String(length=140), nullable=True),
        sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('result_count', sa.Integer(), nullable=False),
        sa.Column('clicked_provider_id', sa.Integer(), nullable=True),
        sa.Column('booked_provider_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['booked_provider_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['clicked_provider_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('search_query_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_search_query_logs_booked_provider_id'), ['booked_provider_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_search_query_logs_clicked_provider_id'), ['clicked_provider_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_search_query_logs_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_search_query_logs_query_text'), ['query_text'], unique=False)
            batch_op.create_index(batch_op.f('ix_search_query_logs_session_id'), ['session_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_search_query_logs_user_id'), ['user_id'], unique=False)

    if not _table_exists('user_subscriptions'):
        op.create_table('user_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('status', _named_enum(bind, 'membershipstatus'), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('ends_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_subscriptions_plan_id'), ['plan_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_subscriptions_user_id'), ['user_id'], unique=False)

    if not _table_exists('notification_deliveries'):
        op.create_table('notification_deliveries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('notification_id', sa.Integer(), nullable=False),
        sa.Column('channel', _named_enum(bind, 'notificationchannel'), nullable=False),
        sa.Column('status', _named_enum(bind, 'notificationdeliverystatus'), nullable=False),
        sa.Column('template_key', sa.String(length=64), nullable=False),
        sa.Column('template_version', sa.Integer(), nullable=False),
        sa.Column('provider_message_id', sa.String(length=128), nullable=True),
        sa.Column('error_code', sa.String(length=64), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('attempted_at', sa.DateTime(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notification_deliveries_notification_id'), ['notification_id'], unique=False)

    if not _table_exists('provider_availability_rules'):
        op.create_table('provider_availability_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=True),
        sa.Column('weekday', sa.Integer(), nullable=False),
        sa.Column('start_minute_local', sa.Integer(), nullable=False),
        sa.Column('end_minute_local', sa.Integer(), nullable=False),
        sa.Column('buffer_before_minutes', sa.Integer(), nullable=False),
        sa.Column('buffer_after_minutes', sa.Integer(), nullable=False),
        sa.Column('min_notice_minutes', sa.Integer(), nullable=False),
        sa.Column('max_advance_days', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('provider_availability_rules', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_provider_availability_rules_enabled'), ['enabled'], unique=False)
            batch_op.create_index(batch_op.f('ix_provider_availability_rules_provider_id'), ['provider_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_provider_availability_rules_skill_id'), ['skill_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_provider_availability_rules_weekday'), ['weekday'], unique=False)

    if not _table_exists('quote_requests'):
        op.create_table('quote_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('seeker_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=True),
        sa.Column('service_title', sa.String(length=150), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('address_text', sa.String(length=255), nullable=True),
        sa.Column('preferred_window_start', sa.DateTime(), nullable=True),
        sa.Column('preferred_window_end', sa.DateTime(), nullable=True),
        sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('status', _named_enum(bind, 'quoterequeststatus'), nullable=False),
        sa.Column('accepted_provider_quote_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('provider_quotes'):
        op.create_table('provider_quotes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quote_request_id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('revision_number', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('line_items', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
        sa.Column('earliest_available_at', sa.DateTime(), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('status', _named_enum(bind, 'providerquotestatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('provider_quotes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_provider_quotes_provider_id'), ['provider_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_provider_quotes_quote_request_id'), ['quote_request_id'], unique=False)

    if not _table_exists('quote_messages'):
        op.create_table('quote_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quote_request_id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('message_type', _named_enum(bind, 'quotemessagetype'), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('quote_messages', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_quote_messages_quote_request_id'), ['quote_request_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_quote_messages_sender_id'), ['sender_id'], unique=False)

    if not _table_exists('quote_request_provider_targets'):
        op.create_table('quote_request_provider_targets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quote_request_id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('target_status', _named_enum(bind, 'quotetargetstatus'), nullable=False),
        sa.Column('first_notified_at', sa.DateTime(), nullable=True),
        sa.Column('response_due_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('quote_request_provider_targets', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_quote_request_provider_targets_provider_id'), ['provider_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_quote_request_provider_targets_quote_request_id'), ['quote_request_id'], unique=False)

    if not _table_exists('booking_disputes'):
        op.create_table('booking_disputes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('opened_by_user_id', sa.Integer(), nullable=False),
        sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
        sa.Column('status', _named_enum(bind, 'disputestatus'), nullable=False),
        sa.Column('category', sa.String(length=64), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('resolution_notes', sa.Text(), nullable=True),
        sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('booking_disputes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_booking_disputes_assigned_admin_id'), ['assigned_admin_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_booking_disputes_booking_id'), ['booking_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_booking_disputes_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_booking_disputes_opened_by_user_id'), ['opened_by_user_id'], unique=False)

    if not _table_exists('booking_timeline_events'):
        op.create_table('booking_timeline_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('actor_user_id', sa.Integer(), nullable=True),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('booking_timeline_events', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_booking_timeline_events_actor_user_id'), ['actor_user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_booking_timeline_events_booking_id'), ['booking_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_booking_timeline_events_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_booking_timeline_events_event_type'), ['event_type'], unique=False)

    if not _table_exists('fraud_flags'):
        op.create_table('fraud_flags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('fraud_flags', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_fraud_flags_booking_id'), ['booking_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_fraud_flags_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_fraud_flags_user_id'), ['user_id'], unique=False)

    if not _table_exists('promo_redemptions'):
        op.create_table('promo_redemptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('promo_code_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('promo_redemptions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_promo_redemptions_booking_id'), ['booking_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_promo_redemptions_promo_code_id'), ['promo_code_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_promo_redemptions_user_id'), ['user_id'], unique=False)

    if not _table_exists('referral_rewards'):
        op.create_table('referral_rewards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('referrer_user_id', sa.Integer(), nullable=False),
        sa.Column('referred_user_id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('status', _named_enum(bind, 'referralrewardstatus'), nullable=False),
        sa.Column('reward_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('note', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('referral_rewards', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_referral_rewards_booking_id'), ['booking_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_referral_rewards_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_referral_rewards_referred_user_id'), ['referred_user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_referral_rewards_referrer_user_id'), ['referrer_user_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        if _column_exists('audit_log', 'actor_id'):
            # Only drop indexes if they exist
            # Note: batch_op.drop_index might fail if index name is wrong
            try:
                batch_op.drop_index('idx_audit_actor')
                batch_op.drop_index('idx_audit_event')
                batch_op.drop_index('idx_audit_target')
            except:
                pass
            batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_log_target_id'), ['target_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_log_target_type'), ['target_type'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        if not _column_exists('bookings', 'is_deleted'):
            batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
        if not _column_exists('bookings', 'deleted_at'):
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        if not _column_exists('bookings', 'cgst_amount'):
            batch_op.add_column(sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
        if not _column_exists('bookings', 'sgst_amount'):
            batch_op.add_column(sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
        if not _column_exists('bookings', 'igst_amount'):
            batch_op.add_column(sa.Column('igst_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
        if not _column_exists('bookings', 'sac_code'):
            batch_op.add_column(sa.Column('sac_code', sa.String(length=20), nullable=True, server_default='998599'))
        if not _column_exists('bookings', 'payment_method'):
            batch_op.add_column(sa.Column('payment_method', sa.String(length=32), nullable=True, server_default='online'))
        if not _column_exists('bookings', 'cash_collected_at'):
            batch_op.add_column(sa.Column('cash_collected_at', sa.DateTime(), nullable=True))
        if not _column_exists('bookings', 'cash_collected_by'):
            batch_op.add_column(sa.Column('cash_collected_by', sa.Integer(), nullable=True))
        if not _column_exists('bookings', 'refund_amount'):
            batch_op.add_column(sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
        
        batch_op.alter_column('gst_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('service_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        try:
            batch_op.drop_index('ix_bookings_provider_status')
            batch_op.drop_index('ix_bookings_seeker_status')
        except:
            pass
        # Foreign key might already exist if we used create_all
        # but Alembic tracks it separately.
        # Actually, op.create_foreign_key is safer.

    with op.batch_alter_table('messages', schema=None) as batch_op:
        if not _column_exists('messages', 'is_deleted'):
            batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
        if not _column_exists('messages', 'deleted_at'):
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        try:
            batch_op.drop_index('ix_messages_room_created')
        except:
            pass

    with op.batch_alter_table('skills', schema=None) as batch_op:
        try:
            batch_op.drop_index('ix_skills_provider_active')
        except:
            pass

    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_provider_active'), ['provider_id', 'is_active'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_room_created'), ['room', 'created_at'], unique=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_bookings_seeker_status'), ['seeker_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_provider_status'), ['provider_id', 'status'], unique=False)
        batch_op.alter_column('service_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('gst_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.create_index(batch_op.f('idx_audit_target'), ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_event'), ['event_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_actor'), ['actor_id', 'created_at'], unique=False)

    with op.batch_alter_table('referral_rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_rewards_referrer_user_id'))
        batch_op.drop_index(batch_op.f('ix_referral_rewards_referred_user_id'))
        batch_op.drop_index(batch_op.f('ix_referral_rewards_created_at'))
        batch_op.drop_index(batch_op.f('ix_referral_rewards_booking_id'))

    op.drop_table('referral_rewards')
    with op.batch_alter_table('promo_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_redemptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_promo_redemptions_promo_code_id'))
        batch_op.drop_index(batch_op.f('ix_promo_redemptions_booking_id'))

    op.drop_table('promo_redemptions')
    with op.batch_alter_table('fraud_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_flags_user_id'))
        batch_op.drop_index(batch_op.f('ix_fraud_flags_created_at'))
        batch_op.drop_index(batch_op.f('ix_fraud_flags_booking_id'))

    op.drop_table('fraud_flags')
    with op.batch_alter_table('booking_timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_timeline_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_booking_timeline_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_booking_timeline_events_booking_id'))
        batch_op.drop_index(batch_op.f('ix_booking_timeline_events_actor_user_id'))

    op.drop_table('booking_timeline_events')
    with op.batch_alter_table('booking_disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_disputes_opened_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_disputes_created_at'))
        batch_op.drop_index(batch_op.f('ix_booking_disputes_booking_id'))
        batch_op.drop_index(batch_op.f('ix_booking_disputes_assigned_admin_id'))

    op.drop_table('booking_disputes')
    with op.batch_alter_table('quote_request_provider_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_request_provider_targets_quote_request_id'))
        batch_op.drop_index(batch_op.f('ix_quote_request_provider_targets_provider_id'))

    op.drop_table('quote_request_provider_targets')
    with op.batch_alter_table('quote_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_quote_messages_quote_request_id'))

    op.drop_table('quote_messages')
    with op.batch_alter_table('provider_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_quotes_quote_request_id'))
        batch_op.drop_index(batch_op.f('ix_provider_quotes_provider_id'))

    op.drop_table('provider_quotes')
    op.drop_table('quote_requests')
    with op.batch_alter_table('provider_availability_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_availability_rules_weekday'))
        batch_op.drop_index(batch_op.f('ix_provider_availability_rules_skill_id'))
        batch_op.drop_index(batch_op.f('ix_provider_availability_rules_provider_id'))
        batch_op.drop_index(batch_op.f('ix_provider_availability_rules_enabled'))

    op.drop_table('provider_availability_rules')
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_notification_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_plan_id'))

    op.drop_table('user_subscriptions')
    with op.batch_alter_table('search_query_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_query_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_query_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_search_query_logs_query_text'))
        batch_op.drop_index(batch_op.f('ix_search_query_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_search_query_logs_clicked_provider_id'))
        batch_op.drop_index(batch_op.f('ix_search_query_logs_booked_provider_id'))

    op.drop_table('search_query_logs')
    with op.batch_alter_table('provider_instant_book_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_instant_book_settings_provider_id'))

    op.drop_table('provider_instant_book_settings')
    with op.batch_alter_table('provider_blackouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_blackouts_start_at'))
        batch_op.drop_index(batch_op.f('ix_provider_blackouts_provider_id'))
        batch_op.drop_index(batch_op.f('ix_provider_blackouts_end_at'))

    op.drop_table('provider_blackouts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('booking_change_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_change_policies_provider_id'))

    op.drop_table('booking_change_policies')
    with op.batch_alter_table('ai_job_intake_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_job_intake_logs_user_id'))

    op.drop_table('ai_job_intake_logs')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('subscription_plans')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))

    op.drop_table('promo_codes')
    with op.batch_alter_table('chat_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_insights_room'))

    op.drop_table('chat_insights')
    # ### end Alembic commands ###
