"""add webhook events

Revision ID: cf9f3f01712b
Revises: 0cb53a43798b
Create Date: 2026-04-09 07:56:37.516570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9f3f01712b'  # pragma: allowlist secret
down_revision = '0cb53a43798b'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'webhook_events' not in tables:
        op.create_table('webhook_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.String(length=128), nullable=False),
        sa.Column('provider', sa.String(length=32), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('webhook_events', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_webhook_events_event_id'), ['event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_id'))

    op.drop_table('webhook_events')
    # ### end Alembic commands ###
