"""add gst invoice fields

Revision ID: ec34e6b07788
Revises: 7112d2f636fc
Create Date: 2026-04-09 11:56:15.665851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec34e6b07788'  # pragma: allowlist secret
down_revision = '7112d2f636fc'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_url', sa.String(length=1024), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gstin', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gstin')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('invoice_url')

    # ### end Alembic commands ###
